# 📊 Pandas 데이터 조작 완전정복
## 데이터 선택, 변경, 변형, 병합

### 수업 목표
- **필요 데이터 선택하기**: loc, iloc, 불리언 인덱싱, query() 등으로 원하는 데이터를 추출할 수 있다
- **필요 데이터 변경하기**: 값 수정, 컬럼 추가/삭제, 데이터 타입 변환, 결측치 처리를 할 수 있다
- **데이터프레임 변형하기**: pivot, melt, stack/unstack, 피벗테이블을 활용할 수 있다
- **데이터프레임 병합하기**: merge, concat, join으로 여러 데이터프레임을 결합할 수 있다

### 수업 구성 (3시간)
| 시간 | 내용 | 사용 데이터 |
|------|------|------------|
| 1교시 (50분) | 데이터 로드 + 필요 데이터 선택하기 | 컴퓨터 가격, 상하수도요금 |
| 2교시 (50분) | 필요 데이터 변경하기 | 컴퓨터 가격, 상하수도요금 |
| 3교시 (80분) | 데이터프레임 변형하기 + 병합하기 + 연습문제 | 3개 데이터 모두 |

---

# 🕐 1교시: 데이터 로드 + 필요 데이터 선택하기
---
## 1-1. 라이브러리 임포트 및 데이터 로드

In [1]:
# 필요한 라이브러리 임포트
import pandas as pd
import numpy as np

# pandas 출력 옵션 설정
pd.set_option('display.max_columns', 15)     # 최대 표시 컬럼 수
pd.set_option('display.max_rows', 30)        # 최대 표시 행 수
pd.set_option('display.float_format', '{:,.1f}'.format)  # 숫자 천단위 콤마

print("라이브러리 로드 완료!")

라이브러리 로드 완료!

In [2]:
# 데이터 1: 컴퓨터 가격 데이터 (영문, 10만 건)
df_comp = pd.read_csv('pandas/data/computer_prices_all.csv')
print(f"컴퓨터 가격 데이터: {df_comp.shape[0]:,}행 × {df_comp.shape[1]}열")
df_comp.head()

컴퓨터 가격 데이터: 100,000행 × 33열

,device_type,brand,model,release_year,os,form_factor,cpu_brand,...,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
0,Desktop,Samsung,Samsung Forge XDI,2022,Windows,ATX,Intel,...,0,750,Wi-Fi 6,5.1,11.0,36,"1,384.0"
1,Laptop,Samsung,Samsung Pro KM8,2022,Windows,Mainstream,Intel,...,120,0,Wi-Fi 6,5.3,2.0,12,"2,275.0"
2,Desktop,Lenovo,Lenovo Strix BIE,2024,macOS,SFF,AMD,...,0,850,Wi-Fi 6,5.0,7.0,24,"1,880.0"
3,Desktop,Dell,Dell Cube AXR,2024,Windows,ATX,AMD,...,0,650,Wi-Fi 6,5.2,6.0,36,"1,332.0"
4,Laptop,Gigabyte,Gigabyte Pro IX1,2024,Linux,Gaming,AMD,...,90,0,Wi-Fi 6,5.2,1.5,12,"2,682.0"

In [3]:
# 데이터 2: 경상북도 안동시 상하수도 요금정보 (한글, 47만 건)
df_water = pd.read_csv('pandas/data/경상북도 안동시_상하수도요금정보_20251124.csv', encoding='cp949')
print(f"상하수도 요금 데이터: {df_water.shape[0]:,}행 × {df_water.shape[1]}열")
df_water.head()

상하수도 요금 데이터: 471,984행 × 6열

        수용가번호 읍면동명   업종  사용량    사용요금       납기마감일
0  1001020000  중구동  일반용   14   13310  2025-11-24
1  1001030000  중구동  일반용    2    1900  2025-11-24
2  1001040000  중구동  일반용  152  315890  2025-11-24
3  1001050000  중구동  일반용    2    1900  2025-11-24
4  1001060000  중구동  일반용   31   38060  2025-11-24

In [4]:
# 데이터 3: 국세청 사업자현황 성별 데이터 (한글, 8,527건)
df_biz = pd.read_csv('pandas/data/국세청_사업자현황_성별_20240930.csv', encoding='cp949')
print(f"사업자현황 데이터: {df_biz.shape[0]:,}행 × {df_biz.shape[1]}열")
df_biz.head()

사업자현황 데이터: 8,527행 × 13열

,업태별,시도,시군구,성별,(전체)당월,(전체)전월,(전체)전년동월,(개인)당월,(개인)전월,(개인)전년동월,(법인)당월,(법인)전월,(법인)전년동월
0,농·임·어업,서울특별시,종로구,남자,19,19,19,5,5,6,14,14,13
1,농·임·어업,서울특별시,종로구,여자,5,5,4,3,3,3,0,0,0
2,농·임·어업,서울특별시,중구,남자,11,11,10,0,0,0,9,9,8
3,농·임·어업,서울특별시,중구,여자,0,0,0,0,0,0,0,0,0
4,농·임·어업,서울특별시,용산구,남자,7,7,7,3,3,3,4,4,4

In [5]:
# 각 데이터의 컬럼 정보 확인
print("=== 컴퓨터 가격 데이터 컬럼 ===")
print(df_comp.columns.tolist())
print()
print("=== 상하수도 요금 데이터 컬럼 ===")
print(df_water.columns.tolist())
print()
print("=== 사업자현황 데이터 컬럼 ===")
print(df_biz.columns.tolist())

=== 컴퓨터 가격 데이터 컬럼 ===
['device_type', 'brand', 'model', 'release_year', 'os', 'form_factor', 'cpu_brand', 'cpu_model', 'cpu_tier', 'cpu_cores', 'cpu_threads', 'cpu_base_ghz', 'cpu_boost_ghz', 'gpu_brand', 'gpu_model', 'gpu_tier', 'vram_gb', 'ram_gb', 'storage_type', 'storage_gb', 'storage_drive_count', 'display_type', 'display_size_in', 'resolution', 'refresh_hz', 'battery_wh', 'charger_watts', 'psu_watts', 'wifi', 'bluetooth', 'weight_kg', 'warranty_months', 'price']

=== 상하수도 요금 데이터 컬럼 ===
['수용가번호', '읍면동명', '업종', '사용량', '사용요금', '납기마감일']

=== 사업자현황 데이터 컬럼 ===
['업태별', '시도', '시군구', '성별', '(전체)당월', '(전체)전월', '(전체)전년동월', '(개인)당월', '(개인)전월', '(개인)전년동월', '(법인)당월', '(법인)전월', '(법인)전년동월']

## 1-2. 컬럼(열) 선택하기

> 데이터프레임에서 원하는 컬럼만 추출하는 방법입니다.
>
> | 방법 | 문법 | 반환 타입 |
> |------|------|----------|
> | 단일 컬럼 (대괄호) | `df['컬럼명']` | Series |
> | 단일 컬럼 (점 표기) | `df.컬럼명` | Series |
> | 여러 컬럼 | `df[['컬럼1', '컬럼2']]` | DataFrame |

In [6]:
# 단일 컬럼 선택 - Series로 반환
# 대괄호 방식: 컬럼명에 공백이나 특수문자가 있어도 사용 가능
print(type(df_comp['brand']))  # Series 타입 확인
df_comp['brand'].head(10)

<class 'pandas.core.series.Series'>

0     Samsung
1     Samsung
2      Lenovo
3        Dell
4    Gigabyte
5         MSI
6       Apple
7       Apple
8        Dell
9      Lenovo
Name: brand, dtype: object

In [7]:
# 점(dot) 표기법 - 컬럼명에 공백이 없을 때만 사용 가능
# 주의: 컬럼명이 파이썬 예약어(class, type 등)이거나 공백 포함 시 사용 불가
df_comp.brand.head(5)

0     Samsung
1     Samsung
2      Lenovo
3        Dell
4    Gigabyte
Name: brand, dtype: object

In [8]:
# 여러 컬럼 선택 - 리스트로 컬럼명을 전달하면 DataFrame으로 반환
# 컴퓨터 데이터에서 브랜드, 모델, RAM, 가격 컬럼만 추출
df_comp_selected = df_comp[['brand', 'model', 'ram_gb', 'price']]
print(type(df_comp_selected))  # DataFrame 타입 확인
df_comp_selected.head()

<class 'pandas.core.frame.DataFrame'>

      brand              model  ram_gb   price
0   Samsung  Samsung Forge XDI      16 1,384.0
1   Samsung    Samsung Pro KM8      64 2,275.0
2    Lenovo   Lenovo Strix BIE       8 1,880.0
3      Dell      Dell Cube AXR      16 1,332.0
4  Gigabyte   Gigabyte Pro IX1      96 2,682.0

In [9]:
# 한글 컬럼명도 동일하게 사용 가능
# 상하수도 데이터에서 읍면동명, 업종, 사용요금만 추출
df_water[['읍면동명', '업종', '사용요금']].head()

  읍면동명   업종    사용요금
0  중구동  일반용   13310
1  중구동  일반용    1900
2  중구동  일반용  315890
3  중구동  일반용    1900
4  중구동  일반용   38060

In [10]:
# filter() 메서드로 컬럼 선택 - 컬럼명 패턴으로 필터링
# like: 특정 문자열이 포함된 컬럼 선택
# regex: 정규식 패턴에 맞는 컬럼 선택

# '전체'가 포함된 컬럼만 선택 (사업자현황 데이터)
print("=== '전체'가 포함된 컬럼 ===")
print(df_biz.filter(like='전체').head())
print()

# 'cpu'로 시작하는 컬럼만 선택 (컴퓨터 데이터)
print("=== 'cpu'로 시작하는 컬럼 ===")
df_comp.filter(regex='^cpu').head()

=== '전체'가 포함된 컬럼 ===
   (전체)당월  (전체)전월  (전체)전년동월
0      19      19        19
1       5       5         4
2      11      11        10
3       0       0         0
4       7       7         7

=== 'cpu'로 시작하는 컬럼 ===

,cpu_brand,cpu_model,cpu_tier,cpu_cores,cpu_threads,cpu_base_ghz,cpu_boost_ghz
0,Intel,Intel i5-11129,3,12,24,2.8,3.8
1,Intel,Intel i7-11114,4,12,24,2.6,3.6
2,AMD,AMD Ryzen 5 5168,2,8,16,2.6,3.6
3,AMD,AMD Ryzen 5 7550,2,6,12,2.6,3.6
4,AMD,AMD Ryzen 7 6230,5,16,32,2.8,3.9

## 1-3. 행(row) 선택하기 - 인덱스 기반

> 행을 선택하는 두 가지 핵심 접근자(accessor):
>
> | 접근자 | 기준 | 예시 |
> |--------|------|------|
> | `loc[]` | **라벨(이름)** 기반 | `df.loc[0:5]` → 0~5행 **포함** |
> | `iloc[]` | **정수 위치** 기반 | `df.iloc[0:5]` → 0~4행 (5 **미포함**) |
>
> ⚠️ **핵심 차이**: `loc`은 끝 값을 **포함**, `iloc`은 끝 값을 **미포함** (파이썬 슬라이싱과 동일)

In [11]:
# iloc - 정수 위치 기반 인덱싱
# 첫 번째 행 (인덱스 0)
print("=== 첫 번째 행 (iloc[0]) ===")
print(df_comp.iloc[0])
print()

# 처음 3행 선택 (0, 1, 2번째 행) - 끝 값 미포함
print("=== 처음 3행 (iloc[0:3]) ===")
df_comp.iloc[0:3]

=== 첫 번째 행 (iloc[0]) ===
device_type                  Desktop
brand                        Samsung
model              Samsung Forge XDI
release_year                    2022
os                           Windows
                         ...
wifi                         Wi-Fi 6
bluetooth                        5.1
weight_kg                       11.0
warranty_months                   36
price                        1,384.0
Name: 0, Length: 33, dtype: object

=== 처음 3행 (iloc[0:3]) ===

,device_type,brand,model,release_year,os,form_factor,cpu_brand,...,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
0,Desktop,Samsung,Samsung Forge XDI,2022,Windows,ATX,Intel,...,0,750,Wi-Fi 6,5.1,11.0,36,"1,384.0"
1,Laptop,Samsung,Samsung Pro KM8,2022,Windows,Mainstream,Intel,...,120,0,Wi-Fi 6,5.3,2.0,12,"2,275.0"
2,Desktop,Lenovo,Lenovo Strix BIE,2024,macOS,SFF,AMD,...,0,850,Wi-Fi 6,5.0,7.0,24,"1,880.0"

In [12]:
# iloc - 행과 열을 동시에 선택 (행, 열 모두 정수 위치)
# df.iloc[행범위, 열범위]
# 처음 5행, 처음 4열 선택
print("=== iloc[0:5, 0:4] - 5행 × 4열 ===")
print(df_comp.iloc[0:5, 0:4])
print()

# 특정 행과 열을 리스트로 선택
# 0, 2, 4번째 행의 1, 3, 5번째 열
print("=== iloc[[0,2,4], [1,3,5]] - 특정 위치 선택 ===")
df_comp.iloc[[0, 2, 4], [1, 3, 5]]

=== iloc[0:5, 0:4] - 5행 × 4열 ===
  device_type     brand              model  release_year
0     Desktop   Samsung  Samsung Forge XDI          2022
1      Laptop   Samsung    Samsung Pro KM8          2022
2     Desktop    Lenovo   Lenovo Strix BIE          2024
3     Desktop      Dell      Dell Cube AXR          2024
4      Laptop  Gigabyte   Gigabyte Pro IX1          2024

=== iloc[[0,2,4], [1,3,5]] - 특정 위치 선택 ===

      brand  release_year form_factor
0   Samsung          2022         ATX
2    Lenovo          2024         SFF
4  Gigabyte          2024      Gaming

In [13]:
# loc - 라벨 기반 인덱싱
# loc은 인덱스 라벨과 컬럼명을 사용하여 데이터 선택
# 인덱스 0~4행, 'brand'부터 'os'까지 컬럼 선택 (끝 값 포함!)
print("=== loc[0:4, 'brand':'os'] - 라벨 기반, 끝 값 포함 ===")
df_comp.loc[0:4, 'brand':'os']

=== loc[0:4, 'brand':'os'] - 라벨 기반, 끝 값 포함 ===

      brand              model  release_year       os
0   Samsung  Samsung Forge XDI          2022  Windows
1   Samsung    Samsung Pro KM8          2022  Windows
2    Lenovo   Lenovo Strix BIE          2024    macOS
3      Dell      Dell Cube AXR          2024  Windows
4  Gigabyte   Gigabyte Pro IX1          2024    Linux

In [14]:
# loc - 특정 행과 특정 컬럼을 리스트로 선택
# 인덱스 [0, 10, 100]번 행의 ['brand', 'ram_gb', 'price'] 컬럼
df_comp.loc[[0, 10, 100], ['brand', 'ram_gb', 'price']]

        brand  ram_gb   price
0     Samsung      16 1,384.0
10         HP      16 1,372.0
100  Gigabyte      32 1,763.0

In [15]:
# loc vs iloc 차이 비교 - 슬라이싱 끝 값 처리
print("=== loc[0:3] → 0, 1, 2, 3 (4행, 끝 값 포함) ===")
print(df_water.loc[0:3, '읍면동명':'사용량'])
print()
print("=== iloc[0:3] → 0, 1, 2 (3행, 끝 값 미포함) ===")
print(df_water.iloc[0:3, 1:4])

=== loc[0:3] → 0, 1, 2, 3 (4행, 끝 값 포함) ===
  읍면동명   업종  사용량
0  중구동  일반용   14
1  중구동  일반용    2
2  중구동  일반용  152
3  중구동  일반용    2

=== iloc[0:3] → 0, 1, 2 (3행, 끝 값 미포함) ===
  읍면동명   업종  사용량
0  중구동  일반용   14
1  중구동  일반용    2
2  중구동  일반용  152

## 1-4. 조건으로 행 선택하기 (불리언 인덱싱)

> 데이터 분석에서 **가장 많이 사용**하는 데이터 선택 방법입니다.
> 
> ```python
> # 기본 문법
> df[df['컬럼'] 비교연산자 값]
> 
> # 여러 조건 결합
> df[(조건1) & (조건2)]   # AND
> df[(조건1) | (조건2)]   # OR
> df[~(조건)]             # NOT
> ```
> ⚠️ 주의: 여러 조건을 결합할 때 각 조건을 반드시 **괄호**로 감싸야 합니다.

In [16]:
# 단일 조건 - 가격이 3000달러 이상인 컴퓨터
# 비교 연산 결과는 True/False의 불리언 Series
expensive = df_comp[df_comp['price'] >= 3000]
print(f"3000달러 이상 컴퓨터: {len(expensive):,}건 / 전체 {len(df_comp):,}건")
expensive[['brand', 'model', 'ram_gb', 'price']].head()

3000달러 이상 컴퓨터: 4,388건 / 전체 100,000건

      brand               model  ram_gb   price
17    Apple     Apple Blade 0BN      96 3,422.0
25     Acer      Acer Think VVE     104 3,003.0
26    Apple       Apple Air W7N     144 3,547.0
28  Samsung  Samsung Legion TES     128 3,174.0
34    Apple     Apple Think YDD      96 3,164.0

In [17]:
# 문자열 조건 - 브랜드가 'Apple'인 컴퓨터
apple = df_comp[df_comp['brand'] == 'Apple']
print(f"Apple 컴퓨터: {len(apple):,}건")
apple[['brand', 'model', 'device_type', 'price']].head()

Apple 컴퓨터: 11,915건

    brand              model device_type   price
6   Apple    Apple Arena R5Q     Desktop 1,610.0
7   Apple  Apple Station EWP     Desktop 2,140.0
17  Apple    Apple Blade 0BN      Laptop 3,422.0
22  Apple     Apple Cube 1S3     Desktop 2,531.0
26  Apple      Apple Air W7N      Laptop 3,547.0

In [80]:
# 여러 조건 AND(&) - Apple 브랜드이면서 RAM 32GB 이상
# 각 조건을 괄호로 감싸야 함
apple_high_ram = df_comp[(df_comp['brand'] == 'Apple') & (df_comp['ram_gb'] >= 32)]
print(f"Apple + RAM 32GB 이상: {len(apple_high_ram):,}건")
print(apple_high_ram[['brand', 'model', 'ram_gb', 'price']].head())
print(apple_high_ram['price'].mean().round(2))

Apple + RAM 32GB 이상: 8,321건
    brand              model  ram_gb   price
7   Apple  Apple Station EWP      32 2,140.0
17  Apple    Apple Blade 0BN      96 3,422.0
22  Apple     Apple Cube 1S3      96 2,531.0
26  Apple      Apple Air W7N     144 3,547.0
34  Apple    Apple Think YDD      96 3,164.0
2630.11

In [19]:
# 여러 조건 OR(|) - 상하수도 데이터에서 산업용 또는 영업용
industrial_or_business = df_water[(df_water['업종'] == '산업용') | (df_water['업종'] == '영업용')]
print(f"산업용 또는 영업용: {len(industrial_or_business):,}건")
industrial_or_business.head()

산업용 또는 영업용: 1,920건

           수용가번호 읍면동명   업종  사용량    사용요금       납기마감일
265   1005090000  중구동  산업용    1    1050  2025-11-24
4325  3150122500  용상동  산업용  181  190050  2025-11-24
4715  3190940001  용상동  산업용   42   44100  2025-11-24
5775  3430050001  용상동  산업용   81   85050  2025-11-24
5802  3430230001  용상동  산업용   49   51450  2025-11-24

In [20]:
# NOT(~) 조건 - 일반용이 아닌 데이터만 선택
not_general = df_water[~(df_water['업종'] == '일반용')]
print(f"일반용 제외: {len(not_general):,}건")
print(f"포함된 업종: {not_general['업종'].unique()}")

일반용 제외: 386,880건
포함된 업종: ['일반겸용' '가정용' '산업용' '욕탕용' '욕탕겸용']

In [21]:
# isin() - 여러 값 중 하나에 해당하는 행 선택 (OR 조건의 간편 버전)
# 브랜드가 Apple, Dell, HP 중 하나인 컴퓨터
target_brands = ['Apple', 'Dell', 'HP']
filtered = df_comp[df_comp['brand'].isin(target_brands)]
print(f"Apple/Dell/HP 컴퓨터: {len(filtered):,}건")
print(filtered['brand'].value_counts())

Apple/Dell/HP 컴퓨터: 40,034건
brand
HP       14114
Dell     14005
Apple    11915
Name: count, dtype: int64

In [22]:
# between() - 범위 조건 (이상 & 이하를 한 번에)
# 가격이 1000~2000 사이인 컴퓨터
mid_price = df_comp[df_comp['price'].between(1000, 2000)]
print(f"1000~2000달러 컴퓨터: {len(mid_price):,}건")
mid_price[['brand', 'model', 'price']].head()

1000~2000달러 컴퓨터: 56,799건

     brand              model   price
0  Samsung  Samsung Forge XDI 1,384.0
2   Lenovo   Lenovo Strix BIE 1,880.0
3     Dell      Dell Cube AXR 1,332.0
6    Apple    Apple Arena R5Q 1,610.0
9   Lenovo   Lenovo Blade MIZ 1,654.0

## 1-5. 문자열 조건으로 선택하기 (str 접근자)

> 문자열 컬럼에 `str` 접근자를 사용하면 다양한 문자열 조건으로 필터링할 수 있습니다.
>
> | 메서드 | 설명 |
> |--------|------|
> | `str.contains('문자열')` | 특정 문자열 포함 여부 |
> | `str.startswith('문자열')` | 특정 문자열로 시작 |
> | `str.endswith('문자열')` | 특정 문자열로 끝남 |
> | `str.len()` | 문자열 길이 |

In [23]:
# str.contains() - 모델명에 'Pro'가 포함된 컴퓨터
pro_models = df_comp[df_comp['model'].str.contains('Pro')]
print(f"'Pro' 모델: {len(pro_models):,}건")
pro_models[['brand', 'model', 'price']].head()

'Pro' 모델: 11,013건

       brand             model   price
1    Samsung   Samsung Pro KM8 2,275.0
4   Gigabyte  Gigabyte Pro IX1 2,682.0
10        HP        HP Pro 6XS 1,372.0
20        HP        HP Pro 2WA 1,124.0
50    Lenovo    Lenovo Pro 2DS 2,279.0

In [24]:
# str.startswith() - 읍면동명이 '풍'으로 시작하는 지역
feng_areas = df_water[df_water['읍면동명'].str.startswith('풍')]
print(f"'풍'으로 시작하는 읍면동: {feng_areas['읍면동명'].unique()}")
print(f"건수: {len(feng_areas):,}건")

'풍'으로 시작하는 읍면동: ['풍산읍' '풍천면']
건수: 73,176건

In [25]:
# str.contains() + 대소문자 무시 (case=False)
# GPU 모델명에 'rtx'가 포함된 컴퓨터 (대소문자 구분 없이)
rtx_gpu = df_comp[df_comp['gpu_model'].str.contains('rtx', case=False)]
print(f"RTX GPU 컴퓨터: {len(rtx_gpu):,}건")
print(f"GPU 모델 종류: {rtx_gpu['gpu_model'].nunique()}개")
rtx_gpu['gpu_model'].value_counts().head(10)

RTX GPU 컴퓨터: 54,712건
GPU 모델 종류: 18개

gpu_model
RTX 40 70       5743
RTX 30 70       5692
RTX 40 60       5437
RTX 30 60       5314
RTX 30 50       5046
RTX 40 50       4970
RTX 40 80       4676
RTX 30 80       4618
RTX 30 80 Ti    2752
RTX 40 80 Ti    2685
Name: count, dtype: int64

## 1-6. query() 메서드로 선택하기

> `query()`는 문자열 표현식으로 조건을 작성하여, 더 읽기 쉬운 코드를 작성할 수 있습니다.
>
> ```python
> # 불리언 인덱싱 방식 (길고 복잡)
> df[(df['price'] >= 1000) & (df['brand'] == 'Apple')]
>
> # query() 방식 (짧고 간결)
> df.query("price >= 1000 and brand == 'Apple'")
> ```

In [26]:
# query() 기본 사용 - and, or, not 키워드 사용 가능
# Dell 브랜드이면서 RAM이 32GB 이상이고 가격이 2000 이하인 컴퓨터
result = df_comp.query("brand == 'Dell' and ram_gb >= 32 and price <= 2000")
print(f"조건에 맞는 컴퓨터: {len(result):,}건")
result[['brand', 'model', 'ram_gb', 'price']].head()

조건에 맞는 컴퓨터: 2,706건

    brand             model  ram_gb   price
122  Dell      Dell Pro NXA      64 1,784.0
174  Dell  Dell Stealth SZR      32 1,940.0
175  Dell    Dell Nitro 7K5      32 1,626.0
251  Dell  Dell Station MKG      64 1,903.0
304  Dell    Dell Forge 4BZ      32 1,969.0

In [27]:
# query()에서 외부 변수 사용 - @ 기호를 붙여 참조
# 특정 가격 기준 이상인 컴퓨터 필터링
min_price = 2500
max_price = 3500
result = df_comp.query("@min_price <= price <= @max_price")
print(f"{min_price}~{max_price}달러 컴퓨터: {len(result):,}건")
result[['brand', 'model', 'price']].head()

2500~3500달러 컴퓨터: 15,198건

       brand             model   price
4   Gigabyte  Gigabyte Pro IX1 2,682.0
5        MSI     MSI Think KSG 2,752.0
8       Dell  Dell Creator GIQ 2,954.0
13      Acer  Acer Station XDV 2,762.0
16      Acer      Acer Zen NYU 2,679.0

In [28]:
# query()에서 in 연산자와 한글 컬럼명(백틱) 사용
# 한글 컬럼명은 백틱(`)으로 감싸야 함
result = df_water.query("`업종` in ['산업용', '영업용'] and `사용요금` >= 100000")
print(f"산업용/영업용 중 10만원 이상: {len(result):,}건")
result.head()

산업용/영업용 중 10만원 이상: 534건

            수용가번호 읍면동명   업종   사용량     사용요금       납기마감일
4325   3150122500  용상동  산업용   181   190050  2025-11-24
6252   3442365000  용상동  산업용  5914  6209700  2025-11-24
13298  6310130001  강남동  산업용  1033  1084650  2025-11-24
13379  6310725000  강남동  산업용   304   319200  2025-11-24
13390  6310810010  강남동  산업용   483   507150  2025-11-24

## 1-7. 기타 유용한 선택 방법

In [29]:
# head(), tail() - 상위/하위 N행 선택
print("=== 상위 3행 ===")
print(df_water.head(3))
print()
print("=== 하위 3행 ===")
print(df_water.tail(3))

=== 상위 3행 ===
        수용가번호 읍면동명   업종  사용량    사용요금       납기마감일
0  1001020000  중구동  일반용   14   13310  2025-11-24
1  1001030000  중구동  일반용    2    1900  2025-11-24
2  1001040000  중구동  일반용  152  315890  2025-11-24

=== 하위 3행 ===
              수용가번호 읍면동명   업종  사용량   사용요금       납기마감일
471981  42130440000  예안면  가정용    5   2370  2025-11-24
471982  42130450000  예안면  가정용   17  12460  2025-11-24
471983  42130460000  예안면  가정용    0      0  2025-11-24

In [30]:
# nlargest(), nsmallest() - 특정 컬럼 기준 상위/하위 N행
# 가격이 가장 높은 컴퓨터 5대
print("=== 가격 TOP 5 ===")
print(df_comp.nlargest(5, 'price')[['brand', 'model', 'ram_gb', 'price']])
print()

# 사용요금이 가장 낮은 5건 (0 제외)
print("=== 사용요금 하위 5 (0 제외) ===")
df_water[df_water['사용요금'] > 0].nsmallest(5, '사용요금')

=== 가격 TOP 5 ===
        brand              model  ram_gb    price
40823  Lenovo     Lenovo Pro KMZ      96 10,985.0
54591   Apple      Apple Pro XVG      64  9,773.0
64831      HP       HP Think 1FC      96  9,634.0
75607     MSI        MSI Pro 8M3      64  9,622.0
69792   Apple  Apple Station N4Y      64  9,545.0

=== 사용요금 하위 5 (0 제외) ===

          수용가번호 읍면동명   업종  사용량  사용요금       납기마감일
196  1004080000  중구동  가정용    1   470  2025-11-24
342  1006260000  중구동  가정용    1   470  2025-11-24
391  1007370000  중구동  가정용    1   470  2025-11-24
559  1009670001  중구동  가정용    1   470  2025-11-24
583  1010130010  중구동  가정용    1   470  2025-11-24

In [31]:
# sample() - 랜덤 샘플링
# n: 개수 지정, frac: 비율 지정, random_state: 재현성을 위한 시드
print("=== 랜덤 5건 추출 ===")
print(df_comp.sample(n=5, random_state=42)[['brand', 'model', 'price']])
print()

# 전체의 0.01% 랜덤 추출
print("=== 전체의 0.01% 랜덤 추출 ===")
sampled = df_comp.sample(frac=0.0001, random_state=42)
print(f"추출 건수: {len(sampled)}건")
sampled[['brand', 'model', 'price']]

=== 랜덤 5건 추출 ===
         brand                model   price
75721  Samsung  Samsung Creator QO3 1,737.0
80184   Lenovo       Lenovo Pro 5R2 1,460.0
19864     Acer         Acer Pro 7SY 2,009.0
76699  Samsung  Samsung Stealth 5EW 2,790.0
92991      MSI      MSI Creator V90 1,422.0

=== 전체의 0.01% 랜덤 추출 ===
추출 건수: 10건

         brand                model   price
75721  Samsung  Samsung Creator QO3 1,737.0
80184   Lenovo       Lenovo Pro 5R2 1,460.0
19864     Acer         Acer Pro 7SY 2,009.0
76699  Samsung  Samsung Stealth 5EW 2,790.0
92991      MSI      MSI Creator V90 1,422.0
76434   Lenovo     Lenovo Think K2V 1,140.0
84004    Apple      Apple Arena 2GM 2,115.0
80917     ASUS       ASUS Forge NRI 2,759.0
60767     ASUS       ASUS Think 27I 1,247.0
50074    Apple     Apple Legion 1H6 1,718.0

In [32]:
# drop_duplicates() - 중복 제거 후 고유값만 선택
# 컴퓨터 데이터에서 브랜드별 고유 device_type 조합만 추출
unique_combos = df_comp[['brand', 'device_type']].drop_duplicates()
print(f"브랜드-기기유형 고유 조합: {len(unique_combos)}개")
unique_combos.sort_values(['brand', 'device_type'])

브랜드-기기유형 고유 조합: 20개

       brand device_type
19      ASUS     Desktop
43      ASUS      Laptop
13      Acer     Desktop
16      Acer      Laptop
6      Apple     Desktop
17     Apple      Laptop
3       Dell     Desktop
8       Dell      Laptop
63  Gigabyte     Desktop
4   Gigabyte      Laptop
12        HP     Desktop
10        HP      Laptop
2     Lenovo     Desktop
9     Lenovo      Laptop
5        MSI     Desktop
46       MSI      Laptop
52     Razer     Desktop
74     Razer      Laptop
0    Samsung     Desktop
1    Samsung      Laptop

# 🕐 2교시: 필요 데이터 변경하기
---
## 2-1. 값 수정하기

> 데이터를 분석하기 전에 잘못된 값을 수정하거나 새로운 값을 할당해야 할 때가 많습니다.
>
> | 방법 | 문법 | 용도 |
> |------|------|------|
> | 직접 할당 | `df['컬럼'] = 값` | 전체 컬럼 수정 |
> | loc 할당 | `df.loc[조건, '컬럼'] = 값` | 조건에 맞는 행만 수정 |
> | replace() | `df['컬럼'].replace(old, new)` | 특정 값을 다른 값으로 치환 |
> | where/mask | `df['컬럼'].where(조건, 대체값)` | 조건부 값 변경 |

In [33]:
# 실습용 데이터 복사 (원본 보존을 위해 copy() 사용)
df_c = df_comp.copy()
df_w = df_water.copy()

# loc으로 조건에 맞는 행의 특정 컬럼 값 변경
# 예: 가격이 0 이하인 행의 가격을 NaN으로 변경
print(f"변경 전 - 가격 0 이하: {(df_c['price'] <= 0).sum()}건")
df_c.loc[df_c['price'] <= 0, 'price'] = np.nan
print(f"변경 후 - 가격 NaN: {df_c['price'].isna().sum()}건")

변경 전 - 가격 0 이하: 0건
변경 후 - 가격 NaN: 0건

In [34]:
# replace() - 특정 값을 다른 값으로 치환
# 상하수도 데이터에서 업종명 변경
df_w['업종'] = df_w['업종'].replace({
    '일반용': '가정·일반용',     # '일반용'을 '가정·일반용'으로 변경
    '영업용': '상업·영업용'      # '영업용'을 '상업·영업용'으로 변경
})
print("변경 후 업종 목록:")
print(df_w['업종'].value_counts())

변경 후 업종 목록:
업종
가정용       372864
가정·일반용     85104
일반겸용       11892
산업용         1920
욕탕용          192
욕탕겸용          12
Name: count, dtype: int64

In [35]:
# np.where() - 조건에 따라 다른 값 할당 (엑셀의 IF 함수와 유사)
# 가격이 2000 이상이면 '고가', 미만이면 '보통'
df_c = df_comp.copy()
df_c['가격대'] = np.where(df_c['price'] >= 2000, '고가', '보통')
print(df_c['가격대'].value_counts())
print()

# np.select() - 여러 조건에 따라 다른 값 할당
# 가격 구간별 등급 부여
conditions = [
    df_c['price'] < 1000,           # 1000 미만
    df_c['price'].between(1000, 2000),  # 1000~2000
    df_c['price'].between(2000, 3000),  # 2000~3000
    df_c['price'] >= 3000           # 3000 이상
]
choices = ['저가', '중저가', '중고가', '고가']
df_c['가격등급'] = np.select(conditions, choices, default='미분류')
print(df_c['가격등급'].value_counts())

가격대
보통    58996
고가    41004
Name: count, dtype: int64

가격등급
중저가    56799
중고가    36616
고가      4388
저가      2197
Name: count, dtype: int64

## 2-2. 컬럼 추가 및 삭제

In [36]:
# 새 컬럼 추가 - 기존 컬럼을 이용한 연산
df_c = df_comp.copy()

# 1) 산술 연산으로 새 컬럼 생성
# CPU 부스트 클럭과 기본 클럭의 차이
df_c['cpu_boost_diff'] = df_c['cpu_boost_ghz'] - df_c['cpu_base_ghz']

# 2) 문자열 결합으로 새 컬럼 생성
# 브랜드 + 기기유형 결합
df_c['brand_type'] = df_c['brand'] + ' - ' + df_c['device_type']

# 3) GB당 가격 계산 (가격 / RAM 용량)
df_c['price_per_gb_ram'] = (df_c['price'] / df_c['ram_gb']).round(2)

df_c[['brand_type', 'cpu_boost_diff', 'ram_gb', 'price', 'price_per_gb_ram']].head()

          brand_type  cpu_boost_diff  ram_gb   price  price_per_gb_ram
0  Samsung - Desktop             1.0      16 1,384.0              86.5
1   Samsung - Laptop             1.0      64 2,275.0              35.5
2   Lenovo - Desktop             1.0       8 1,880.0             235.0
3     Dell - Desktop             1.0      16 1,332.0              83.2
4  Gigabyte - Laptop             1.1      96 2,682.0              27.9

In [37]:
# assign() - 체이닝 방식으로 여러 컬럼 한 번에 추가 (원본 변경 없이 새 DataFrame 반환)
df_comp.assign(
    # 톤당 요금 환산 (1톤 = 사용량 기준)
    total_threads_per_core=lambda x: x['cpu_threads'] / x['cpu_cores'],
    # 가격대 구분
    price_category=lambda x: pd.cut(x['price'], bins=[0, 1000, 2000, 3000, float('inf')],
                                     labels=['저가', '중저가', '중고가', '고가'])
)[['brand', 'cpu_cores', 'cpu_threads', 'total_threads_per_core', 'price', 'price_category']].head()

,brand,cpu_cores,cpu_threads,total_threads_per_core,price,price_category
0,Samsung,12,24,2.0,"1,384.0",중저가
1,Samsung,12,24,2.0,"2,275.0",중고가
2,Lenovo,8,16,2.0,"1,880.0",중저가
3,Dell,6,12,2.0,"1,332.0",중저가
4,Gigabyte,16,32,2.0,"2,682.0",중고가

In [38]:
# 컬럼 삭제 - drop() 메서드
df_c = df_comp.copy()

# 단일 컬럼 삭제 (axis=1 또는 columns 파라미터 사용)
df_dropped = df_c.drop(columns=['bluetooth', 'wifi'])
print(f"삭제 전 컬럼 수: {len(df_c.columns)} → 삭제 후: {len(df_dropped.columns)}")
print(f"삭제된 컬럼: bluetooth, wifi")
print()

# 여러 컬럼 삭제
cols_to_drop = ['psu_watts', 'charger_watts', 'battery_wh']
df_dropped2 = df_c.drop(columns=cols_to_drop)
print(f"추가 삭제 후 컬럼 수: {len(df_dropped2.columns)}")
print(f"남은 컬럼: {df_dropped2.columns.tolist()}")

삭제 전 컬럼 수: 33 → 삭제 후: 31
삭제된 컬럼: bluetooth, wifi

추가 삭제 후 컬럼 수: 30
남은 컬럼: ['device_type', 'brand', 'model', 'release_year', 'os', 'form_factor', 'cpu_brand', 'cpu_model', 'cpu_tier', 'cpu_cores', 'cpu_threads', 'cpu_base_ghz', 'cpu_boost_ghz', 'gpu_brand', 'gpu_model', 'gpu_tier', 'vram_gb', 'ram_gb', 'storage_type', 'storage_gb', 'storage_drive_count', 'display_type', 'display_size_in', 'resolution', 'refresh_hz', 'wifi', 'bluetooth', 'weight_kg', 'warranty_months', 'price']

## 2-3. 컬럼명 변경하기

In [39]:
# rename() - 특정 컬럼명만 변경 (딕셔너리: {기존명: 새이름})
df_w = df_water.copy()
df_w = df_w.rename(columns={
    '수용가번호': '고객번호',
    '읍면동명': '지역명',
    '납기마감일': '마감일'
})
print("변경 후 컬럼:", df_w.columns.tolist())
df_w.head(3)

변경 후 컬럼: ['고객번호', '지역명', '업종', '사용량', '사용요금', '마감일']

         고객번호  지역명   업종  사용량    사용요금         마감일
0  1001020000  중구동  일반용   14   13310  2025-11-24
1  1001030000  중구동  일반용    2    1900  2025-11-24
2  1001040000  중구동  일반용  152  315890  2025-11-24

In [40]:
# columns 속성으로 전체 컬럼명을 한 번에 변경
df_w2 = df_water.head(3).copy()
df_w2.columns = ['번호', '지역', '용도', '수량', '요금', '마감일']
print("전체 컬럼명 변경 결과:")
df_w2

전체 컬럼명 변경 결과:

           번호   지역   용도   수량      요금         마감일
0  1001020000  중구동  일반용   14   13310  2025-11-24
1  1001030000  중구동  일반용    2    1900  2025-11-24
2  1001040000  중구동  일반용  152  315890  2025-11-24

In [41]:
# 컬럼명 일괄 변환 - 함수 적용
# str.upper(): 대문자로, str.lower(): 소문자로, str.replace(): 문자 치환
df_c = df_comp.head(3).copy()

# 컬럼명을 모두 대문자로 변경
df_upper = df_c.rename(columns=str.upper)
print("대문자 변환:", df_upper.columns.tolist()[:5])

# 컬럼명의 언더스코어(_)를 공백으로 변경
df_space = df_c.rename(columns=lambda x: x.replace('_', ' '))
print("언더스코어→공백:", df_space.columns.tolist()[:5])

대문자 변환: ['DEVICE_TYPE', 'BRAND', 'MODEL', 'RELEASE_YEAR', 'OS']
언더스코어→공백: ['device type', 'brand', 'model', 'release year', 'os']

## 2-4. 데이터 타입 변환하기

> 데이터 분석 전에 올바른 데이터 타입으로 변환하는 것이 중요합니다.
>
> | 메서드 | 용도 |
> |--------|------|
> | `astype()` | 데이터 타입 강제 변환 |
> | `pd.to_numeric()` | 숫자로 변환 (오류 처리 가능) |
> | `pd.to_datetime()` | 날짜/시간으로 변환 |
> | `pd.Categorical()` | 범주형으로 변환 |

In [42]:
# 현재 데이터 타입 확인
print("=== 상하수도 데이터 타입 ===")
print(df_water.dtypes)
print()
# 납기마감일이 object(문자열)로 되어 있음 → datetime으로 변환 필요

=== 상하수도 데이터 타입 ===
수용가번호     int64
읍면동명     object
업종       object
사용량       int64
사용요금      int64
납기마감일    object
dtype: object

In [43]:
# astype() - 데이터 타입 강제 변환
df_w = df_water.copy()

# 수용가번호를 문자열로 변환 (숫자형이지만 실제로는 ID이므로 문자열이 적절)
df_w['수용가번호'] = df_w['수용가번호'].astype(str)
print(f"수용가번호 타입: {df_w['수용가번호'].dtype}")
print(f"예시: {df_w['수용가번호'].iloc[0]}")
print()

# 사용량을 float으로 변환
df_w['사용량'] = df_w['사용량'].astype(float)
print(f"사용량 타입: {df_w['사용량'].dtype}")

수용가번호 타입: object
예시: 1001020000

사용량 타입: float64

In [44]:
# pd.to_datetime() - 날짜 변환
df_w = df_water.copy()
df_w['납기마감일'] = pd.to_datetime(df_w['납기마감일'])
print(f"변환 후 타입: {df_w['납기마감일'].dtype}")
print()

# 날짜에서 연/월/일/요일 추출
df_w['연도'] = df_w['납기마감일'].dt.year
df_w['월'] = df_w['납기마감일'].dt.month
df_w['일'] = df_w['납기마감일'].dt.day
df_w['요일'] = df_w['납기마감일'].dt.day_name()  # 영문 요일명

df_w[['납기마감일', '연도', '월', '일', '요일']].head()

변환 후 타입: datetime64[ns]

       납기마감일    연도   월   일      요일
0 2025-11-24  2025  11  24  Monday
1 2025-11-24  2025  11  24  Monday
2 2025-11-24  2025  11  24  Monday
3 2025-11-24  2025  11  24  Monday
4 2025-11-24  2025  11  24  Monday

In [45]:
# pd.Categorical() - 범주형 변환 (메모리 절약 + 순서 지정 가능)
df_c = df_comp.copy()

# device_type을 범주형으로 변환
df_c['device_type'] = pd.Categorical(df_c['device_type'])
print(f"타입: {df_c['device_type'].dtype}")
print(f"카테고리: {df_c['device_type'].cat.categories.tolist()}")
print()

# 메모리 사용량 비교
print(f"object 타입 메모리: {df_comp['device_type'].memory_usage():,} bytes")
print(f"category 타입 메모리: {df_c['device_type'].memory_usage():,} bytes")
print(f"절약률: {(1 - df_c['device_type'].memory_usage()/df_comp['device_type'].memory_usage())*100:.1f}%")

타입: category
카테고리: ['Desktop', 'Laptop']

object 타입 메모리: 800,132 bytes
category 타입 메모리: 100,256 bytes
절약률: 87.5%

## 2-5. 결측치(NaN) 처리하기

> 결측치는 분석 결과를 왜곡할 수 있으므로 적절한 처리가 필요합니다.
>
> | 메서드 | 설명 |
> |--------|------|
> | `isna()` / `isnull()` | 결측 여부 확인 (True/False) |
> | `notna()` / `notnull()` | 비결측 여부 확인 |
> | `dropna()` | 결측치가 있는 행/열 삭제 |
> | `fillna()` | 결측치를 특정 값으로 채움 |

In [46]:
# 결측치 확인
print("=== 컴퓨터 데이터 결측치 현황 ===")
print(df_comp.isnull().sum())
print(f"\n총 결측치 수: {df_comp.isnull().sum().sum()}")

=== 컴퓨터 데이터 결측치 현황 ===
device_type        0
brand              0
model              0
release_year       0
os                 0
                  ..
wifi               0
bluetooth          0
weight_kg          0
warranty_months    0
price              0
Length: 33, dtype: int64

총 결측치 수: 0

In [47]:
# 실습을 위해 의도적으로 결측치 생성
df_c = df_comp.head(20).copy()

# 일부 행의 값을 NaN으로 변경
df_c.loc[3, 'price'] = np.nan
df_c.loc[7, 'price'] = np.nan
df_c.loc[5, 'ram_gb'] = np.nan
df_c.loc[12, 'ram_gb'] = np.nan
df_c.loc[15, 'brand'] = np.nan

print("=== 결측치 현황 ===")
print(df_c[['brand', 'ram_gb', 'price']].isnull().sum())
print()

# 결측치가 있는 행만 확인
print("=== 결측치가 있는 행 ===")
df_c[df_c.isnull().any(axis=1)][['brand', 'model', 'ram_gb', 'price']]

=== 결측치 현황 ===
brand     1
ram_gb    2
price     2
dtype: int64

=== 결측치가 있는 행 ===

    brand              model  ram_gb   price
3    Dell      Dell Cube AXR    16.0     NaN
5     MSI      MSI Think KSG     NaN 2,752.0
7   Apple  Apple Station EWP    32.0     NaN
12     HP       HP Arena 42K     NaN 1,508.0
15    NaN     Dell Nitro 614    32.0 2,110.0

In [48]:
# dropna() - 결측치 행 삭제
# how='any': 하나라도 NaN이면 삭제 (기본값)
# how='all': 모든 값이 NaN인 행만 삭제
# subset: 특정 컬럼에서만 결측치 확인
print(f"원본: {len(df_c)}행")

# 기본: 어떤 컬럼이든 NaN이 있으면 삭제
df_dropped = df_c.dropna()
print(f"dropna(): {len(df_dropped)}행")

# 특정 컬럼(price)에 NaN이 있는 행만 삭제
df_dropped_price = df_c.dropna(subset=['price'])
print(f"dropna(subset=['price']): {len(df_dropped_price)}행")

원본: 20행
dropna(): 15행
dropna(subset=['price']): 18행

In [49]:
# fillna() - 결측치를 특정 값으로 채우기
df_filled = df_c.copy()

# 1) 특정 값으로 채우기
df_filled['brand'] = df_filled['brand'].fillna('Unknown')

# 2) 평균값으로 채우기
df_filled['price'] = df_filled['price'].fillna(df_c['price'].mean())

# 3) 중앙값으로 채우기
df_filled['ram_gb'] = df_filled['ram_gb'].fillna(df_c['ram_gb'].median())

print("=== 결측치 채우기 결과 ===")
print(f"남은 결측치: {df_filled[['brand', 'ram_gb', 'price']].isnull().sum().sum()}")
df_filled.loc[[3, 5, 7, 12, 15], ['brand', 'model', 'ram_gb', 'price']]

=== 결측치 채우기 결과 ===
남은 결측치: 0

      brand              model  ram_gb   price
3      Dell      Dell Cube AXR    16.0 2,076.2
5       MSI      MSI Think KSG    32.0 2,752.0
7     Apple  Apple Station EWP    32.0 2,076.2
12       HP       HP Arena 42K    32.0 1,508.0
15  Unknown     Dell Nitro 614    32.0 2,110.0

## 2-6. 정렬하기

In [50]:
# sort_values() - 특정 컬럼 기준 정렬
# 가격 기준 내림차순 정렬
print("=== 가격 내림차순 TOP 5 ===")
print(df_comp.sort_values('price', ascending=False)[['brand', 'model', 'price']].head())
print()

# 여러 컬럼 기준 정렬 - 브랜드 오름차순 → 가격 내림차순
print("=== 브랜드 오름차순 → 가격 내림차순 ===")
df_comp.sort_values(['brand', 'price'], ascending=[True, False])[['brand', 'model', 'price']].head(10)

=== 가격 내림차순 TOP 5 ===
        brand              model    price
40823  Lenovo     Lenovo Pro KMZ 10,985.0
54591   Apple      Apple Pro XVG  9,773.0
64831      HP       HP Think 1FC  9,634.0
75607     MSI        MSI Pro 8M3  9,622.0
69792   Apple  Apple Station N4Y  9,545.0

=== 브랜드 오름차순 → 가격 내림차순 ===

      brand             model   price
41921  ASUS      ASUS Pro 6RY 8,103.0
16781  ASUS     ASUS Cube 0S1 6,984.0
96312  ASUS    ASUS Think URT 5,294.0
46704  ASUS      ASUS Air 7G4 4,596.0
19603  ASUS    ASUS Nitro ZE0 4,098.0
60882  ASUS  ASUS Stealth XJU 3,910.0
9244   ASUS    ASUS Nitro UAN 3,759.0
2305   ASUS   ASUS Legion I2O 3,673.0
22877  ASUS      ASUS Zen ARV 3,671.0
10038  ASUS  ASUS Stealth 97F 3,656.0

In [51]:
# sort_index() - 인덱스 기준 정렬
# 인덱스가 섞인 경우 원래 순서로 복원할 때 유용
df_shuffled = df_water.sample(10, random_state=42)
print("=== 셔플된 상태 (인덱스가 뒤섞임) ===")
print(df_shuffled[['읍면동명', '사용요금']].head())
print()

print("=== sort_index() 적용 후 (인덱스 순서로 복원) ===")
df_shuffled.sort_index()[['읍면동명', '사용요금']].head()

=== 셔플된 상태 (인덱스가 뒤섞임) ===
       읍면동명   사용요금
40249   중구동  14260
392792  녹전면      0
30771   풍천면  16880
377357  일직면      0
141544  일직면      0

=== sort_index() 적용 후 (인덱스 순서로 복원) ===

       읍면동명   사용요금
30771   풍천면  16880
40249   중구동  14260
111456  풍천면   2850
141544  일직면      0
175908  풍산읍   4740

## 2-7. 문자열 데이터 변경하기 (str 접근자)

In [52]:
# str 접근자를 이용한 문자열 변환
df_c = df_comp.head(10).copy()

# str.upper() / str.lower() - 대소문자 변환
print("=== 브랜드 대문자 변환 ===")
print(df_c['brand'].str.upper().head())
print()

# str.replace() - 문자열 치환
# 모델명에서 브랜드명 제거
df_c['model_short'] = df_c['model'].str.replace(df_c['brand'] + ' ', '', regex=False)
print("=== 모델명 단축 ===")
df_c[['brand', 'model', 'model_short']].head()

=== 브랜드 대문자 변환 ===
0     SAMSUNG
1     SAMSUNG
2      LENOVO
3        DELL
4    GIGABYTE
Name: brand, dtype: object

=== 모델명 단축 ===

      brand              model  model_short
0   Samsung  Samsung Forge XDI          NaN
1   Samsung    Samsung Pro KM8          NaN
2    Lenovo   Lenovo Strix BIE          NaN
3      Dell      Dell Cube AXR          NaN
4  Gigabyte   Gigabyte Pro IX1          NaN

In [53]:
# str.split() - 문자열 분리
# 해상도(resolution)를 가로/세로로 분리
df_c = df_comp.head(10).copy()

# 'x'를 기준으로 분리하여 새 컬럼 생성
df_c[['해상도_가로', '해상도_세로']] = df_c['resolution'].str.split('x', expand=True)
df_c[['resolution', '해상도_가로', '해상도_세로']].head()

# expand=True: 분리 결과를 별도 컬럼으로 반환 (DataFrame)
# expand=False: 리스트로 반환 (Series)

  resolution 해상도_가로 해상도_세로
0  2560x1440   2560   1440
1  1920x1080   1920   1080
2  3440x1440   3440   1440
3  3440x1440   3440   1440
4  2560x1600   2560   1600

In [54]:
# apply()와 map()으로 값 변환하기
df_c = df_comp.head(10).copy()

# map() - Series의 각 값을 딕셔너리 또는 함수로 매핑
# OS 이름을 한글로 변환
os_map = {'Windows': '윈도우', 'macOS': '맥OS', 'Linux': '리눅스', 'ChromeOS': '크롬OS'}
df_c['os_한글'] = df_c['os'].map(os_map)
print("=== map() 결과 ===")
print(df_c[['os', 'os_한글']].head())
print()

# apply() - 각 값에 사용자 정의 함수 적용
# 가격을 원화로 변환 (1달러 = 1,350원 가정)
df_c['가격_원화'] = df_c['price'].apply(lambda x: f"{x * 1350:,.0f}원")
print("=== apply() 결과 ===")
df_c[['brand', 'price', '가격_원화']].head()

=== map() 결과 ===
        os os_한글
0  Windows   윈도우
1  Windows   윈도우
2    macOS   맥OS
3  Windows   윈도우
4    Linux   리눅스

=== apply() 결과 ===

      brand   price       가격_원화
0   Samsung 1,384.0  1,868,386원
1   Samsung 2,275.0  3,071,236원
2    Lenovo 1,880.0  2,537,986원
3      Dell 1,332.0  1,798,186원
4  Gigabyte 2,682.0  3,620,686원

# 🕐 3교시: 데이터프레임 변형하기 + 병합하기
---
## 3-1. pivot_table() - 피벗 테이블

> 피벗 테이블은 데이터를 요약하는 **교차표**를 만드는 강력한 도구입니다.
> 엑셀의 피벗 테이블과 동일한 개념입니다.
>
> ```python
> pd.pivot_table(
>     data=df,           # 데이터프레임
>     values='집계값',    # 집계할 컬럼
>     index='행',         # 행 기준
>     columns='열',       # 열 기준
>     aggfunc='mean'     # 집계 함수 (기본값: mean)
> )
> ```

In [55]:
# 기본 피벗 테이블 - 상하수도 데이터
# 행: 읍면동명, 열: 업종, 값: 사용요금의 평균
pivot1 = pd.pivot_table(
    df_water,
    values='사용요금',       # 집계할 값
    index='읍면동명',        # 행 기준
    columns='업종',          # 열 기준
    aggfunc='mean'           # 평균 계산
).round(0)

print("=== 읍면동 × 업종별 평균 사용요금 ===")
pivot1.head(10)

=== 읍면동 × 업종별 평균 사용요금 ===

업종        가정용         산업용      욕탕겸용         욕탕용      일반겸용       일반용
읍면동명
강남동  58,755.0   108,672.0       NaN         NaN  38,440.0 109,056.0
길안면  10,110.0   348,973.0       NaN   363,344.0 123,631.0  66,731.0
남후면   8,438.0   101,003.0       NaN         NaN       NaN  90,550.0
녹전면   6,686.0    44,250.0       NaN         NaN       NaN  19,649.0
도산면   7,579.0         NaN       NaN         NaN  18,393.0 118,086.0
명륜동  22,315.0         NaN       NaN 1,415,821.0  35,663.0  64,260.0
북후면   8,652.0 1,069,134.0       NaN         NaN       NaN  43,329.0
서구동  20,956.0     8,713.0 140,338.0   594,531.0  25,595.0  71,590.0
서후면   9,192.0    84,344.0       NaN         NaN  24,865.0  54,131.0
송현동  68,877.0   265,862.0       NaN       752.0  41,676.0 135,753.0

In [56]:
# 여러 집계 함수를 동시에 적용하는 피벗 테이블
# 컴퓨터 데이터: 브랜드 × 기기유형별 가격의 평균과 건수
pivot2 = pd.pivot_table(
    df_comp,
    values='price',
    index='brand',
    columns='device_type',
    aggfunc=['mean', 'count'],    # 여러 집계 함수
    fill_value=0                  # 결측치를 0으로 채움
).round(0)

print("=== 브랜드 × 기기유형별 가격 평균 & 건수 ===")
pivot2

=== 브랜드 × 기기유형별 가격 평균 & 건수 ===

               mean           count
device_type Desktop  Laptop Desktop Laptop
brand
ASUS        1,736.0 1,923.0    4066   6093
Acer        1,657.0 1,827.0    3881   6044
Apple       2,229.0 2,452.0    4785   7130
Dell        1,779.0 1,953.0    5634   8371
Gigabyte    1,763.0 1,939.0    2025   2875
HP          1,752.0 1,930.0    5752   8362
Lenovo      1,764.0 1,936.0    6485   9507
MSI         1,809.0 1,972.0    3218   4673
Razer       1,966.0 2,153.0    1192   1841
Samsung     1,808.0 2,007.0    3118   4948

In [57]:
# margins=True - 소계/합계 행과 열 추가
# 사업자현황: 시도별/성별 전체 사업자 수 + 합계
pivot3 = pd.pivot_table(
    df_biz,
    values='(전체)당월',
    index='시도',
    columns='성별',
    aggfunc='sum',
    margins=True,           # 합계 행/열 추가
    margins_name='합계'      # 합계 이름 지정
)

print("=== 시도 × 성별 사업자 수 (합계 포함) ===")
pivot3

=== 시도 × 성별 사업자 수 (합계 포함) ===

성별            남자     미상       여자        합계
시도
강원특별자치도   176294    679   126251    303224
경기도      1691751   2743  1158507   2853001
경상남도      334767    687   225742    561196
경상북도      284175    476   176993    461644
광주광역시     148268    274   101388    249930
대구광역시     251749    314   157132    409195
대전광역시     151378    498   102814    254690
부산광역시     348847    341   244654    593842
서울특별시    1250509   4428   849804   2104741
세종특별자치시    36508    107    31794     68409
울산광역시      98621    161    71064    169846
인천광역시     338443    338   244602    583383
전라남도      211106    289   136839    348234
전북특별자치도   203443    278   137401    341122
제주특별자치도    93523    263    69220    163006
충청남도      250229    514   162650    413393
충청북도      179899    745   113132    293776
합계       6049510  13135  4109987  10172632

## 3-2. melt() - 넓은 형태를 긴 형태로 변환 (Unpivot)

> `melt()`는 **wide format → long format** 변환입니다. pivot의 반대 작업입니다.
>
> ```
> Wide format (넓은 형태):        Long format (긴 형태):
> 이름  국어  영어  수학          이름  과목  점수
> 김    90   80   70   →        김   국어   90
> 이    85   95   80             김   영어   80
>                                김   수학   70
>                                이   국어   85
>                                ...
> ```

In [58]:
# 사업자현황 데이터가 melt의 좋은 예제
# (전체)당월, (전체)전월, (전체)전년동월 → 하나의 '기간' 컬럼으로 변환
print("=== 변환 전 (Wide 형태) ===")
print(df_biz[['업태별', '시도', '성별', '(전체)당월', '(전체)전월', '(전체)전년동월']].head(3))
print()

# melt 적용
df_biz_melted = df_biz.melt(
    id_vars=['업태별', '시도', '시군구', '성별'],   # 유지할 컬럼 (식별자)
    value_vars=['(전체)당월', '(전체)전월', '(전체)전년동월'],  # 녹일 컬럼
    var_name='기간',           # 새로 생성될 변수명 컬럼 이름
    value_name='사업자수'       # 새로 생성될 값 컬럼 이름
)

print("=== 변환 후 (Long 형태) ===")
print(f"크기: {df_biz_melted.shape}")
df_biz_melted.head(9)

=== 변환 전 (Wide 형태) ===
      업태별     시도  성별  (전체)당월  (전체)전월  (전체)전년동월
0  농·임·어업  서울특별시  남자      19      19        19
1  농·임·어업  서울특별시  여자       5       5         4
2  농·임·어업  서울특별시  남자      11      11        10

=== 변환 후 (Long 형태) ===
크기: (25581, 6)

      업태별     시도  시군구  성별      기간  사업자수
0  농·임·어업  서울특별시  종로구  남자  (전체)당월    19
1  농·임·어업  서울특별시  종로구  여자  (전체)당월     5
2  농·임·어업  서울특별시   중구  남자  (전체)당월    11
3  농·임·어업  서울특별시   중구  여자  (전체)당월     0
4  농·임·어업  서울특별시  용산구  남자  (전체)당월     7
5  농·임·어업  서울특별시  용산구  여자  (전체)당월     9
6  농·임·어업  서울특별시  성동구  남자  (전체)당월    17
7  농·임·어업  서울특별시  성동구  여자  (전체)당월     0
8  농·임·어업  서울특별시  광진구  남자  (전체)당월    30

## 3-3. stack() / unstack() - 인덱스 레벨 변환

> `stack()`과 `unstack()`은 멀티인덱스 레벨을 행↔열로 변환합니다.
>
> - **stack()**: 열 → 행 (컬럼을 인덱스 레벨로 내림)
> - **unstack()**: 행 → 열 (인덱스 레벨을 컬럼으로 올림)

In [59]:
# 먼저 멀티인덱스 데이터를 만들기 (groupby 결과)
# 업종별 × 읍면동별 평균 요금
multi_idx = df_water.groupby(['업종', '읍면동명'])['사용요금'].mean().round(0)
print("=== 멀티인덱스 Series ===")
print(multi_idx.head(10))
print()

# unstack() - 마지막 인덱스 레벨을 컬럼으로 올림
unstacked = multi_idx.unstack(fill_value=0)
print("=== unstack() 결과 (행→열) ===")
unstacked.iloc[:, :5]  # 처음 5개 컬럼만 표시

=== 멀티인덱스 Series ===
업종   읍면동명
가정용  강남동    58,755.0
     길안면    10,110.0
     남후면     8,438.0
     녹전면     6,686.0
     도산면     7,579.0
     명륜동    22,315.0
     북후면     8,652.0
     서구동    20,956.0
     서후면     9,192.0
     송현동    68,877.0
Name: 사용요금, dtype: float64

=== unstack() 결과 (행→열) ===

읍면동명       강남동       길안면       남후면      녹전면       도산면
업종
가정용   58,755.0  10,110.0   8,438.0  6,686.0   7,579.0
산업용  108,672.0 348,973.0 101,003.0 44,250.0       0.0
욕탕겸용       0.0       0.0       0.0      0.0       0.0
욕탕용        0.0 363,344.0       0.0      0.0       0.0
일반겸용  38,440.0 123,631.0       0.0      0.0  18,393.0
일반용  109,056.0  66,731.0  90,550.0 19,649.0 118,086.0

In [60]:
# stack() - 컬럼을 인덱스 레벨로 내림 (unstack의 반대)
stacked = unstacked.stack()
print("=== stack() 결과 (열→행) - 다시 원래 형태로 ===")
stacked.head(10)

=== stack() 결과 (열→행) - 다시 원래 형태로 ===

업종   읍면동명
가정용  강남동    58,755.0
     길안면    10,110.0
     남후면     8,438.0
     녹전면     6,686.0
     도산면     7,579.0
     명륜동    22,315.0
     북후면     8,652.0
     서구동    20,956.0
     서후면     9,192.0
     송현동    68,877.0
dtype: float64

## 3-4. crosstab() - 교차표 만들기

> `pd.crosstab()`은 두 범주형 변수 간의 빈도표(교차표)를 빠르게 만드는 함수입니다.

In [61]:
# 빈도 교차표 - 브랜드 × 기기유형 조합 건수
cross1 = pd.crosstab(df_comp['brand'], df_comp['device_type'])
print("=== 브랜드 × 기기유형 빈도 교차표 ===")
print(cross1)
print()

# normalize 옵션 - 비율로 표시
# normalize='index': 행 기준 비율, 'columns': 열 기준, 'all': 전체 기준
cross_pct = pd.crosstab(df_comp['brand'], df_comp['device_type'], normalize='index')
print("=== 브랜드별 기기유형 비율 (행 기준) ===")
(cross_pct * 100).round(1)

=== 브랜드 × 기기유형 빈도 교차표 ===
device_type  Desktop  Laptop
brand
ASUS            4066    6093
Acer            3881    6044
Apple           4785    7130
Dell            5634    8371
Gigabyte        2025    2875
HP              5752    8362
Lenovo          6485    9507
MSI             3218    4673
Razer           1192    1841
Samsung         3118    4948

=== 브랜드별 기기유형 비율 (행 기준) ===

device_type  Desktop  Laptop
brand
ASUS            40.0    60.0
Acer            39.1    60.9
Apple           40.2    59.8
Dell            40.2    59.8
Gigabyte        41.3    58.7
HP              40.8    59.2
Lenovo          40.6    59.4
MSI             40.8    59.2
Razer           39.3    60.7
Samsung         38.7    61.3

## 3-5. merge() - 데이터프레임 병합 (SQL JOIN과 동일)

> `merge()`는 **공통 키(컬럼)**를 기준으로 두 데이터프레임을 결합합니다.
> SQL의 JOIN과 동일한 개념입니다.
>
> ```python
> pd.merge(left, right, on='공통컬럼', how='inner')
> ```
>
> | how | 설명 | SQL 대응 |
> |-----|------|---------|
> | `inner` | 양쪽 모두 존재하는 키만 (기본값) | INNER JOIN |
> | `left` | 왼쪽 기준, 오른쪽에 없으면 NaN | LEFT JOIN |
> | `right` | 오른쪽 기준, 왼쪽에 없으면 NaN | RIGHT JOIN |
> | `outer` | 양쪽 모두 포함, 없으면 NaN | FULL OUTER JOIN |

In [62]:
# merge 실습을 위한 요약 데이터프레임 생성

# 1) 읍면동별 평균 요금 테이블
df_dong_avg = df_water.groupby('읍면동명').agg(
    평균사용량=('사용량', 'mean'),
    평균요금=('사용요금', 'mean'),
    총건수=('수용가번호', 'count')
).round(1).reset_index()
print("=== 읍면동별 평균 요금 ===")
print(df_dong_avg.head())
print()

# 2) 읍면동별 업종별 건수 테이블
df_dong_type = df_water.groupby(['읍면동명', '업종']).size().reset_index(name='건수')
print("=== 읍면동별 업종 건수 ===")
print(df_dong_type.head())

=== 읍면동별 평균 요금 ===
  읍면동명  평균사용량     평균요금    총건수
0  강남동   69.4 77,989.8  17112
1  길안면   16.0 16,861.4  40056
2  남후면   14.5 16,073.9  13896
3  녹전면    9.1  7,251.8  11244
4  도산면   16.2 24,010.7   7836

=== 읍면동별 업종 건수 ===
  읍면동명    업종     건수
0  강남동   가정용   9084
1  강남동   산업용    276
2  강남동  일반겸용   1056
3  강남동   일반용   6696
4  길안면   가정용  36420

In [63]:
# inner merge (기본값) - 양쪽에 모두 존재하는 읍면동만 결합
merged_inner = pd.merge(df_dong_type, df_dong_avg, on='읍면동명', how='inner')
print(f"=== inner merge 결과: {len(merged_inner)}행 ===")
merged_inner.head(10)

=== inner merge 결과: 85행 ===

  읍면동명    업종     건수  평균사용량     평균요금    총건수
0  강남동   가정용   9084   69.4 77,989.8  17112
1  강남동   산업용    276   69.4 77,989.8  17112
2  강남동  일반겸용   1056   69.4 77,989.8  17112
3  강남동   일반용   6696   69.4 77,989.8  17112
4  길안면   가정용  36420   16.0 16,861.4  40056
5  길안면   산업용    204   16.0 16,861.4  40056
6  길안면   욕탕용     12   16.0 16,861.4  40056
7  길안면  일반겸용     60   16.0 16,861.4  40056
8  길안면   일반용   3360   16.0 16,861.4  40056
9  남후면   가정용  12648   14.5 16,073.9  13896

In [64]:
# left / right / outer merge 비교
# 실습을 위해 일부 데이터만 포함하는 테이블 생성

# 왼쪽: 일부 읍면동만 포함
df_left = df_dong_avg[df_dong_avg['읍면동명'].isin(['중구동', '풍산읍', '와룡면'])].copy()
# 오른쪽: 다른 일부 읍면동만 포함
df_right = df_dong_avg[df_dong_avg['읍면동명'].isin(['중구동', '와룡면', '예안면'])].copy()
df_right = df_right.rename(columns={'평균요금': '평균요금_right', '총건수': '총건수_right'})

print("왼쪽:", df_left['읍면동명'].tolist())
print("오른쪽:", df_right['읍면동명'].tolist())
print()

# 4가지 merge 비교
for how in ['inner', 'left', 'right', 'outer']:
    result = pd.merge(df_left[['읍면동명', '평균요금']], 
                       df_right[['읍면동명', '평균요금_right']], 
                       on='읍면동명', how=how)
    print(f"--- {how} merge ({len(result)}행) ---")
    print(result)
    print()

왼쪽: ['와룡면', '중구동', '풍산읍']
오른쪽: ['예안면', '와룡면', '중구동']

--- inner merge (2행) ---
  읍면동명     평균요금  평균요금_right
0  와룡면  9,169.8     9,169.8
1  중구동 38,072.1    38,072.1

--- left merge (3행) ---
  읍면동명     평균요금  평균요금_right
0  와룡면  9,169.8     9,169.8
1  중구동 38,072.1    38,072.1
2  풍산읍 67,763.9         NaN

--- right merge (3행) ---
  읍면동명     평균요금  평균요금_right
0  예안면      NaN     8,355.1
1  와룡면  9,169.8     9,169.8
2  중구동 38,072.1    38,072.1

--- outer merge (4행) ---
  읍면동명     평균요금  평균요금_right
0  예안면      NaN     8,355.1
1  와룡면  9,169.8     9,169.8
2  중구동 38,072.1    38,072.1
3  풍산읍 67,763.9         NaN

In [65]:
# 키 컬럼명이 다를 때 - left_on, right_on 사용
# 컴퓨터 데이터의 브랜드별 평균 가격 테이블
df_brand_price = df_comp.groupby('brand')['price'].mean().round(0).reset_index()
df_brand_price.columns = ['제조사', '평균가격']  # 컬럼명을 한글로 변경

# '제조사'와 'brand'가 같은 의미이므로 left_on, right_on으로 매핑
merged = pd.merge(
    df_comp[['brand', 'model', 'price']].head(10),
    df_brand_price,
    left_on='brand',        # 왼쪽 DataFrame의 키 컬럼
    right_on='제조사',       # 오른쪽 DataFrame의 키 컬럼
    how='left'
)
print("=== 키 컬럼명이 다른 merge ===")
merged[['brand', 'model', 'price', '평균가격']]

=== 키 컬럼명이 다른 merge ===

      brand              model   price    평균가격
0   Samsung  Samsung Forge XDI 1,384.0 1,930.0
1   Samsung    Samsung Pro KM8 2,275.0 1,930.0
2    Lenovo   Lenovo Strix BIE 1,880.0 1,866.0
3      Dell      Dell Cube AXR 1,332.0 1,883.0
4  Gigabyte   Gigabyte Pro IX1 2,682.0 1,866.0
5       MSI      MSI Think KSG 2,752.0 1,906.0
6     Apple    Apple Arena R5Q 1,610.0 2,362.0
7     Apple  Apple Station EWP 2,140.0 2,362.0
8      Dell   Dell Creator GIQ 2,954.0 1,883.0
9    Lenovo   Lenovo Blade MIZ 1,654.0 1,866.0

## 3-6. concat() - 데이터프레임 연결하기

> `concat()`은 데이터프레임을 **위아래(행 방향)** 또는 **좌우(열 방향)**로 이어 붙입니다.
>
> ```python
> pd.concat([df1, df2], axis=0)  # 행 방향 (위아래)
> pd.concat([df1, df2], axis=1)  # 열 방향 (좌우)
> ```
>
> - merge는 **키(컬럼 값)**를 기준으로 결합
> - concat은 **단순히 이어 붙이기** (키 불필요)

In [66]:
# axis=0 (기본값) - 행 방향 연결 (위아래로 이어 붙이기)
# 컴퓨터 데이터를 기기유형별로 분리 후 다시 합치기

df_desktop = df_comp[df_comp['device_type'] == 'Desktop'].head(3)
df_laptop = df_comp[df_comp['device_type'] == 'Laptop'].head(3)

print(f"Desktop: {len(df_desktop)}행, Laptop: {len(df_laptop)}행")

# 행 방향 연결
df_combined = pd.concat([df_desktop, df_laptop], axis=0, ignore_index=True)
# ignore_index=True: 인덱스를 0부터 재설정
print(f"연결 후: {len(df_combined)}행")
df_combined[['device_type', 'brand', 'model', 'price']]

Desktop: 3행, Laptop: 3행
연결 후: 6행

  device_type     brand              model   price
0     Desktop   Samsung  Samsung Forge XDI 1,384.0
1     Desktop    Lenovo   Lenovo Strix BIE 1,880.0
2     Desktop      Dell      Dell Cube AXR 1,332.0
3      Laptop   Samsung    Samsung Pro KM8 2,275.0
4      Laptop  Gigabyte   Gigabyte Pro IX1 2,682.0
5      Laptop      Dell   Dell Creator GIQ 2,954.0

In [67]:
# axis=1 - 열 방향 연결 (좌우로 이어 붙이기)
# 같은 인덱스의 행끼리 옆으로 결합됨

# 브랜드별 평균 가격과 평균 RAM을 별도로 계산 후 합치기
avg_price = df_comp.groupby('brand')['price'].mean().round(0).rename('평균가격')
avg_ram = df_comp.groupby('brand')['ram_gb'].mean().round(1).rename('평균RAM')

df_brand_stats = pd.concat([avg_price, avg_ram], axis=1)
print("=== 열 방향 연결 (axis=1) ===")
df_brand_stats

=== 열 방향 연결 (axis=1) ===

            평균가격  평균RAM
brand
ASUS     1,848.0   37.9
Acer     1,760.0   37.9
Apple    2,362.0   51.2
Dell     1,883.0   38.0
Gigabyte 1,866.0   39.1
HP       1,857.0   38.6
Lenovo   1,866.0   38.2
MSI      1,906.0   38.0
Razer    2,080.0   38.0
Samsung  1,930.0   37.7

In [68]:
# keys 옵션 - 연결 출처를 구분할 수 있는 레벨 추가
# 여러 데이터를 합칠 때 어디서 온 데이터인지 구분 가능
df_desktop_stats = df_comp[df_comp['device_type'] == 'Desktop'].describe()[['price', 'ram_gb']]
df_laptop_stats = df_comp[df_comp['device_type'] == 'Laptop'].describe()[['price', 'ram_gb']]

# keys로 데이터 출처 표시
combined_stats = pd.concat(
    [df_desktop_stats, df_laptop_stats],
    keys=['Desktop', 'Laptop'],   # 멀티인덱스 레벨 추가
    axis=0
)
print("=== keys를 이용한 출처 구분 ===")
combined_stats

=== keys를 이용한 출처 구분 ===

                 price   ram_gb
Desktop count 40,156.0 40,156.0
        mean   1,819.5     41.6
        std      532.6     32.8
        min      389.0      8.0
        25%    1,434.0     16.0
        50%    1,768.0     32.0
        75%    2,153.0     64.0
        max    9,773.0    144.0
Laptop  count 59,844.0 59,844.0
        mean   2,002.1     38.5
        std      599.5     31.2
        min      373.0      8.0
        25%    1,557.0     16.0
        50%    1,935.0     32.0
        75%    2,379.0     64.0
        max   10,985.0    144.0

## 3-7. join() - 인덱스 기반 병합

> `join()`은 **인덱스**를 기준으로 병합합니다. `merge()`의 간편 버전입니다.

In [69]:
# join() - 인덱스를 기준으로 병합
# 읍면동명을 인덱스로 설정한 두 테이블을 join

# 읍면동별 평균 사용량 (인덱스: 읍면동명)
avg_usage = df_water.groupby('읍면동명')['사용량'].mean().round(1).rename('평균사용량')

# 읍면동별 총 요금 (인덱스: 읍면동명)
total_fee = df_water.groupby('읍면동명')['사용요금'].sum().rename('총요금')

# join으로 인덱스 기반 병합
joined = avg_usage.to_frame().join(total_fee)
print("=== join() 결과 ===")
joined

=== join() 결과 ===

      평균사용량         총요금
읍면동명
강남동    69.4  1334561350
길안면    16.0   675399660
남후면    14.5   223362900
녹전면     9.1    81539230
도산면    16.2   188147750
명륜동    36.1   429109060
북후면    13.4   269187830
서구동    32.0  1221313340
서후면    14.1   280249790
송현동    94.2  1289398790
안기동    39.5   380944760
예안면    10.1    45819150
옥동    204.2  2054364680
와룡면    10.5   238452290
용상동    66.4  2467563950
일직면    13.4   313046270
임동면    16.3   283046390
중구동    29.8   961244790
태화동    30.4   961320560
평화동    33.6   405956620
풍산읍    58.3  2785910090
풍천면    30.8  1371684000

## 3-8. 실전 종합 예제 - 3개 데이터 활용

In [70]:
# 종합 예제 1: 컴퓨터 데이터 - 선택 + 변경 + 변형을 연속 적용
# 목표: 브랜드별 기기유형별 평균 가격 피벗 테이블 + 가격등급 추가

# 1단계: 필요한 컬럼만 선택
df_sub = df_comp[['brand', 'device_type', 'ram_gb', 'storage_gb', 'price']].copy()

# 2단계: 가격등급 컬럼 추가 (변경)
df_sub['가격등급'] = pd.cut(df_sub['price'],
                          bins=[0, 1000, 2000, 3000, float('inf')],
                          labels=['저가', '중저가', '중고가', '고가'])

# 3단계: 피벗 테이블로 변형
pivot_result = pd.pivot_table(
    df_sub,
    values='price',
    index='brand',
    columns='가격등급',
    aggfunc='count',
    fill_value=0,
    observed=True
)

print("=== 브랜드별 가격등급 분포 (건수) ===")
pivot_result

=== 브랜드별 가격등급 분포 (건수) ===

가격등급       저가   중저가   중고가    고가
brand
ASUS      274  6245  3394   246
Acer      394  6618  2780   133
Apple      33  3742  6160  1980
Dell      314  8337  4952   402
Gigabyte  123  2944  1717   116
HP        364  8572  4833   345
Lenovo    359  9740  5480   413
MSI       167  4580  2897   247
Razer      24  1457  1324   228
Samsung   145  4564  3079   278

In [71]:
# 종합 예제 2: 사업자현황 데이터 - melt + merge 활용
# 목표: 개인/법인을 하나의 컬럼으로 변환 후 시도별 비교

# 1단계: 개인/법인 당월 데이터만 선택
df_biz_sub = df_biz[['업태별', '시도', '성별', '(개인)당월', '(법인)당월']].copy()

# 2단계: melt로 개인/법인을 하나의 컬럼으로 변환
df_biz_long = df_biz_sub.melt(
    id_vars=['업태별', '시도', '성별'],
    value_vars=['(개인)당월', '(법인)당월'],
    var_name='사업자구분',
    value_name='사업자수'
)

# 3단계: 사업자구분 값 정리 (변경)
df_biz_long['사업자구분'] = df_biz_long['사업자구분'].replace({
    '(개인)당월': '개인',
    '(법인)당월': '법인'
})

# 4단계: 시도별 사업자구분별 합계 피벗
result = pd.pivot_table(
    df_biz_long,
    values='사업자수',
    index='시도',
    columns='사업자구분',
    aggfunc='sum'
)
result['법인비율(%)'] = (result['법인'] / (result['개인'] + result['법인']) * 100).round(1)

print("=== 시도별 개인/법인 사업자 수 ===")
result.sort_values('법인비율(%)', ascending=False)

=== 시도별 개인/법인 사업자 수 ===

사업자구분         개인      법인  법인비율(%)
시도
서울특별시    1747270  357326     17.0
광주광역시     211592   38332     15.3
전라남도      296407   51733     14.9
충청북도      254992   38735     13.2
전북특별자치도   297009   44048     12.9
경기도      2489899  362870     12.7
충청남도      360962   52369     12.7
제주특별자치도   143075   19911     12.2
대전광역시     223953   30721     12.1
세종특별자치시    60253    8145     11.9
경상북도      406901   54627     11.8
부산광역시     524030   69728     11.7
울산광역시     150606   19227     11.3
강원특별자치도   269169   33980     11.2
경상남도      498929   62185     11.1
인천광역시     522109   61217     10.5
대구광역시     367451   41712     10.2

---
# 📝 실전 연습문제
> 아래 연습문제를 직접 풀어보세요. 초급/중급/고급으로 난이도가 구분되어 있습니다.

### [초급] 연습문제 1 - 데이터 선택
**컴퓨터 데이터에서 Apple 브랜드의 Laptop만 선택하고, brand, model, ram_gb, price 컬럼만 출력하세요. 가격 내림차순으로 상위 10건을 보여주세요.**

> 힌트: 불리언 인덱싱으로 두 조건을 AND(&)로 결합 후, 컬럼을 선택하고 sort_values + head 사용

In [72]:
# 연습문제 1 풀이 공간
# 아래에 코드를 작성하세요


<details>
<summary>💡 연습문제 1 정답 (클릭하여 확인)</summary>

```python
df_comp[(df_comp['brand'] == 'Apple') & (df_comp['device_type'] == 'Laptop')][['brand', 'model', 'ram_gb', 'price']].sort_values('price', ascending=False).head(10)
```
</details>

### [초급] 연습문제 2 - 데이터 변경
**상하수도 데이터에서 사용량이 0인 행의 업종을 '미사용'으로 변경하세요. 변경 후 업종별 건수(value_counts)를 출력하세요.**

> 힌트: `loc[조건, 컬럼]`으로 조건에 맞는 값을 변경

In [73]:
# 연습문제 2 풀이 공간
# 아래에 코드를 작성하세요


<details>
<summary>💡 연습문제 2 정답 (클릭하여 확인)</summary>

```python
df_w = df_water.copy()
df_w.loc[df_w['사용량'] == 0, '업종'] = '미사용'
df_w['업종'].value_counts()
```
</details>

### [중급] 연습문제 3 - query + 변형
**컴퓨터 데이터에서 query()를 사용하여 2023년 이후 출시, RAM 16GB 이상, 가격 2000달러 이하인 노트북을 선택하세요. 그 결과로 브랜드별 OS별 건수를 pivot_table로 만드세요.**

> 힌트: query → 조건 필터링, pivot_table(aggfunc='count')

In [74]:
# 연습문제 3 풀이 공간
# 아래에 코드를 작성하세요


<details>
<summary>💡 연습문제 3 정답 (클릭하여 확인)</summary>

```python
df_filtered = df_comp.query("release_year >= 2023 and ram_gb >= 16 and price <= 2000 and device_type == 'Laptop'")
print(f"조건에 맞는 노트북: {len(df_filtered):,}건")

pd.pivot_table(df_filtered, values='price', index='brand', columns='os', aggfunc='count', fill_value=0)
```
</details>

### [중급] 연습문제 4 - 데이터 변경 + 병합
**컴퓨터 데이터에서 브랜드별 평균 가격 테이블과 브랜드별 평균 RAM 테이블을 각각 만든 후, merge()로 병합하세요. 병합 결과에 'GB당 가격' 컬럼(평균가격/평균RAM)을 추가하세요.**

> 힌트: groupby → mean → reset_index → merge → 새 컬럼 추가

In [75]:
# 연습문제 4 풀이 공간
# 아래에 코드를 작성하세요


<details>
<summary>💡 연습문제 4 정답 (클릭하여 확인)</summary>

```python
# 브랜드별 평균 가격
df_avg_price = df_comp.groupby('brand')['price'].mean().round(0).reset_index()
df_avg_price.columns = ['brand', '평균가격']

# 브랜드별 평균 RAM
df_avg_ram = df_comp.groupby('brand')['ram_gb'].mean().round(1).reset_index()
df_avg_ram.columns = ['brand', '평균RAM']

# merge로 병합
df_merged = pd.merge(df_avg_price, df_avg_ram, on='brand')

# GB당 가격 추가
df_merged['GB당가격'] = (df_merged['평균가격'] / df_merged['평균RAM']).round(1)
df_merged.sort_values('GB당가격')
```
</details>

### [고급] 연습문제 5 - 종합 (선택 + 변경 + 변형 + 병합)
**사업자현황 데이터에서 서울특별시 데이터만 선택하고, (전체)당월과 (전체)전년동월 컬럼을 이용하여 '증감'(당월-전년동월)과 '증감률(%)'((당월-전년동월)/전년동월*100) 컬럼을 추가하세요. 그 결과를 업태별 × 성별 증감률 피벗 테이블로 만드세요.**

> 힌트: 조건 필터링 → 새 컬럼 추가(산술연산) → pivot_table

In [76]:
# 연습문제 5 풀이 공간
# 아래에 코드를 작성하세요


<details>
<summary>💡 연습문제 5 정답 (클릭하여 확인)</summary>

```python
# 1단계: 서울 데이터만 선택
df_seoul = df_biz[df_biz['시도'] == '서울특별시'].copy()

# 2단계: 증감, 증감률 컬럼 추가
df_seoul['증감'] = df_seoul['(전체)당월'] - df_seoul['(전체)전년동월']
df_seoul['증감률(%)'] = np.where(
    df_seoul['(전체)전년동월'] == 0, 0,
    (df_seoul['증감'] / df_seoul['(전체)전년동월'] * 100)
)

# 3단계: 피벗 테이블
pivot = pd.pivot_table(
    df_seoul,
    values='증감률(%)',
    index='업태별',
    columns='성별',
    aggfunc='mean'
).round(1)

pivot.sort_values('남자', ascending=False)
```
</details>

### [고급] 연습문제 6 - concat + merge 종합
**컴퓨터 데이터를 Desktop과 Laptop으로 분리한 후, 각각 브랜드별 평균 가격을 계산하세요. 두 결과를 concat으로 합치되 keys=['Desktop', 'Laptop']으로 출처를 구분하세요. 그 후 unstack()으로 보기 좋은 테이블로 변형하세요.**

> 힌트: 분리 → groupby → concat(keys) → unstack()

In [77]:
# 연습문제 6 풀이 공간
# 아래에 코드를 작성하세요


<details>
<summary>💡 연습문제 6 정답 (클릭하여 확인)</summary>

```python
# 분리
desktop_avg = df_comp[df_comp['device_type'] == 'Desktop'].groupby('brand')['price'].mean().round(0)
laptop_avg = df_comp[df_comp['device_type'] == 'Laptop'].groupby('brand')['price'].mean().round(0)

# concat으로 합치기
combined = pd.concat([desktop_avg, laptop_avg], keys=['Desktop', 'Laptop'])
print("=== concat 결과 ===")
print(combined.head(10))

# unstack으로 변형
result = combined.unstack(level=0)
result['가격차이'] = result['Desktop'] - result['Laptop']
result.sort_values('가격차이', ascending=False)
```
</details>

---
# 수업 정리

### 1교시 - 필요 데이터 선택하기
| 방법 | 문법 | 용도 |
|------|------|------|
| 컬럼 선택 | `df[['col1', 'col2']]` | 원하는 열만 추출 |
| loc | `df.loc[행라벨, 열라벨]` | 라벨 기반 선택 (끝 포함) |
| iloc | `df.iloc[행번호, 열번호]` | 위치 기반 선택 (끝 미포함) |
| 불리언 인덱싱 | `df[df['col'] > 값]` | 조건 기반 행 선택 |
| query() | `df.query("조건식")` | 문자열 기반 조건 선택 |
| isin() | `df[df['col'].isin(리스트)]` | 여러 값 중 하나 |
| str 접근자 | `df['col'].str.contains()` | 문자열 패턴 선택 |

### 2교시 - 필요 데이터 변경하기
| 방법 | 문법 | 용도 |
|------|------|------|
| loc 할당 | `df.loc[조건, 'col'] = 값` | 조건부 값 수정 |
| replace() | `df['col'].replace({old: new})` | 값 치환 |
| np.where() | `np.where(조건, 참, 거짓)` | 이진 분류 |
| np.select() | `np.select(조건리스트, 값리스트)` | 다중 분류 |
| rename() | `df.rename(columns={old: new})` | 컬럼명 변경 |
| astype() | `df['col'].astype(타입)` | 타입 변환 |
| fillna() | `df['col'].fillna(값)` | 결측치 채우기 |
| map() / apply() | `df['col'].map(함수)` | 값 매핑/변환 |

### 3교시 - 변형 + 병합
| 방법 | 문법 | 용도 |
|------|------|------|
| pivot_table() | `pd.pivot_table(df, values, index, columns)` | 교차 요약표 |
| melt() | `df.melt(id_vars, value_vars)` | Wide → Long 변환 |
| stack/unstack | `df.stack()` / `df.unstack()` | 인덱스 레벨 변환 |
| crosstab() | `pd.crosstab(행, 열)` | 빈도 교차표 |
| merge() | `pd.merge(left, right, on, how)` | 키 기반 결합 (JOIN) |
| concat() | `pd.concat([df1, df2], axis)` | 단순 이어 붙이기 |
| join() | `df1.join(df2)` | 인덱스 기반 결합 |

수고하셨습니다! 🎉